
version: "3.9"

services:

  database:
    image: postgis/postgis:latest
    container_name: suha-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urban_heat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
    container_name: suha-backend
    ports:
      - "8000:8000"
    depends_on:
      - database


volumes:

  postgres_data:

