services:

  database:
    image: postgis/postgis:latest
    container_name: suha-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urban_heat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
    container_name: suha-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: suha-frontend
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:

  postgres_data:
